version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend/data:/app/data
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
      - DB_NAME=bd
    depends_on:
      - postgres

  frontend:
    build: ./apps/frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
